<?php

/**
 * @file
 * Block content template functionality.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function block_content_template_theme() {
  return [
    'block_content' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for block_content.
 */
function block_content_template_block_content_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Add theming function when
  // - the $build has a _layout_builder property
  // - the block entity has a view property
  // - the block entity has a _referringItem property
  if (isset($build['_layout_builder']) || isset($entity->view) || isset($entity->_referringItem)) {
    $build['#theme'] = $entity->getEntityTypeId();
  }
}

/**
 * Implements hook_preprocess_HOOK() for "block_content".
 */
function template_preprocess_block_content(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['block_content'] = $variables['elements']['#block_content'];

  $variables['label'] = $variables['block_content']->label();

  $variables['content'] = [];
  if (isset($variables['elements']['_layout_builder'])) {
    $variables['content'][] = $variables['elements']['_layout_builder'];
  }
  else {
    $content = [];
    foreach (Element::children($variables) as $key) {
      $content[] = $variables[$key];
    }
    $variables['content'] = $content;
  }

  // Remove quick edit as it doesn't make sense here. It also points to the view
  // for instance, which doesn't make sense at all.
  if (isset($variables['attributes']['data-quickedit-entity-id'])) {
    unset($variables['attributes']['data-quickedit-entity-id']);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK() for "block_content".
 */
function block_content_template_theme_suggestions_block_content(array $variables) {
  $suggestions = [];
  $block_content = $variables['elements']['#block_content'];

  $suggestions[] = 'block_content__' . $block_content->bundle();
  $suggestions[] = 'block_content__' . $block_content->id();

  return $suggestions;
}
